Feature/ Создание объекта сторис
smmarty/friflex_flutter pull request #17
Opened 2022-11-08 09:34 UTC by aakhlestova

## Description

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore
- [ ] 👨‍💻 Tested

## Screenshots

2022-11-08 10:00 UTC, inoek commented on packages/friflex_stories/pubspec.yaml
> +  cached_network_image: any
нужно прописать версию

2022-11-08 10:00 UTC, inoek commented on packages/friflex_stories/test/friflex_stories_test.dart
> +class MockFriflexStoriesPlatform
если не используешь, то удаляй

2022-11-08 13:06 UTC, petrovyuri commented on packages/friflex_stories/lib/src/story_item.dart
> +
Лучше сразу добавлять описания классов

2022-11-08 13:09 UTC, petrovyuri commented on packages/friflex_stories/lib/src/story_item.dart
> +        CircularProgressIndicator(value: downloadProgress.progress),
Здесь лучше обернуть в виджет Center)

2022-11-08 15:45 UTC, inoek commented on packages/friflex_stories/lib/src/story_item.dart
> +  final String contentURL;
в кемел кейсе у переменных заглавные только первые буквы слов, начиная со второго
соотвественно, contentUrl

2022-11-08 15:45 UTC, inoek commented on packages/friflex_stories/lib/src/story_item.dart
> +
для мвп, в которой может многое поменяться смысла пока мало)

2022-11-08 15:45 UTC, inoek commented on packages/friflex_stories/lib/src/story_item.dart
> +      decoration: BoxDecoration(
это правда

2022-11-08 15:45 UTC, inoek commented on packages/friflex_stories/lib/src/story_item.dart
> +        CircularProgressIndicator(value: downloadProgress.progress),
это задача на будущее

2022-11-08 15:45 UTC, inoek commented on packages/friflex_stories/lib/src/story_item.dart
> +    errorWidget: (context, url, error) => Center(child: Text(error.toString()))/*Icon(Icons.error)*/,
добавь todo

2022-11-08 15:46 UTC, inoek requested changes
поправь мелкие замечания и можешь сливать)

2022-11-08 20:28 UTC, mozerrr commented on packages/friflex_stories/lib/src/story_item.dart
> +  WidgetBuilder get contentBuilder => (context) => CachedNetworkImage(
А стоит ли хардкодить CachedNetworkImage еще и без кастомных параметров?
Что думаете @inoek @petrovyuri ?

2022-11-08 20:29 UTC, mozerrr commented on packages/friflex_stories/pubspec.yaml
> +  sdk: ">=2.17.1 <3.0.0"
если на это нет причин, то зачем?

2022-11-08 20:33 UTC, mozerrr commented on packages/friflex_stories/pubspec.yaml
> +  plugin_platform_interface: ^2.0.2
У меня тут если честно возникает вопрос.
А что если мы также как фаербейз у plugin_platform_interface поменяем апи, из-за этого friflex_stories (прошлая) будет не совместим с будущими версиями?
Что если в friflex_stories зависимости уберем ^ у  plugin_platform_interface, а поставим хардкод? Таким образом если будет меняться версия friflex_stories, то будет если что и меняться plugin_platform_interface. Тогда точно не сломается совместимость.

2022-11-08 20:39 UTC, petrovyuri commented on packages/friflex_stories/lib/src/story_item.dart
> +  WidgetBuilder get contentBuilder => (context) => CachedNetworkImage(
Тут двояко, в принципе ничего плохого нет в хардкоде плагинов внутри плагина. Просто, надо указать, что данная версия 100 процентов работает с данным плагином и зависит от него. В большей части, из-за этого я против ^ внутри плагина.

2022-11-08 20:42 UTC, petrovyuri commented on packages/friflex_stories/lib/src/story_item.dart
> +
Ну, можно просто. Элемент стори) Главное привыкнуть, писать доки на классы)

2022-11-08 20:43 UTC, petrovyuri commented on packages/friflex_stories/pubspec.yaml
> +  sdk: ">=2.17.1 <3.0.0"
В Dart sdk 2.19 будут много ломающих обновлений, я боюсь, что могут быть проблемы.

2022-11-09 05:40 UTC, petrovyuri commented on packages/friflex_stories/pubspec.yaml
> +  plugin_platform_interface: ^2.0.2
Я на самом деле не совсем понял, зачем здесь использовать разделение на платформы)

2022-11-09 05:47 UTC, mozerrr commented on packages/friflex_stories/pubspec.yaml
> +  sdk: ">=2.17.1 <3.0.0"
А зачем тогда использовать сразу 2.19?)

2022-11-09 05:49 UTC, mozerrr commented on packages/friflex_stories/pubspec.yaml
> +  plugin_platform_interface: ^2.0.2
Не знаю насчет платформ, но нам точно нельзя добавлять зависимости, которые могут не пригодиться разработчикам. Допустим зачем мы будем иметь зависимость от конкретного плеера, если их он будет не устраивать?

2022-11-09 05:50 UTC, mozerrr commented on packages/friflex_stories/lib/src/story_item.dart
> +  WidgetBuilder get contentBuilder => (context) => CachedNetworkImage(
Я даже не про версию, а про то, что мы используем CachedNetworkImage и ничего другого. Как быть, если кто-то захочет кастомный лоадер сделать? А кастомное изображение ошибки? И т.д.

2022-11-09 07:56 UTC, inoek commented on packages/friflex_stories/lib/src/story_item.dart
> +  WidgetBuilder get contentBuilder => (context) => CachedNetworkImage(
Это будет в другой задаче

2022-11-09 09:12 UTC, sna2021 commented on packages/friflex_stories/pubspec.yaml
> +  plugin_platform_interface: ^2.0.2
В пакетах  авто инкремент минорных версий ^ является рекомендацией от dart. Без него будут проблемы и варнинги.

2022-11-09 13:02 UTC, inoek approved these changes

2022-11-09 13:04 UTC, merged