[feature-flags] features manager and feature flag
smmarty/friflex_flutter pull request #3
Opened 2022-09-20 13:07 UTC by ksenia312

2022-09-20 16:47 UTC, sna2021 requested changes

2022-09-20 16:47 UTC, sna2021 commented on packages/feature_flags/lib/domain/features_manager.dart
> +  final Map<String, FeatureFlag> _flags = {};
Лучше сделать Map<Type, FeatureFlag>

2022-09-20 16:47 UTC, sna2021 commented on packages/feature_flags/lib/domain/features_manager.dart
> +import 'package:flutter/cupertino.dart';
import 'package:flutter/cupertino.dart';

тут ничего не используется из cupertino
Лучше использовать widget или foundation, зависит от того что импортируем

2022-09-20 16:47 UTC, sna2021 commented on packages/feature_flags/lib/domain/feature_flag.dart
> +  FeatureFlagState? state;
 лучше добавить метод updateState(FeatureFlagState state);
 
 в котором можно будет обновлять состояние, и в разных реализациях FeatureFlag, подменять этот метод. 
 
 FeatureFlagState - сделать не nullable и в конструкторе дать дефолтное initState = FeatureFlagState.disabled.

2022-09-20 16:47 UTC, sna2021 commented on packages/feature_flags/lib/domain/feature_flag.dart
> +  FeatureFlag(FeatureFlagState initState) : state = initState;
initState лучше переименовать в initialState

2022-09-20 16:47 UTC, sna2021 commented on packages/feature_flags/lib/domain/feature_flag.dart
> +  FeatureFlag(FeatureFlagState initState) : state = initState;
короткая запись для этого 

FeatureFlag(this.initState);

 Лучше всегда использовать короткие записи

2022-09-20 16:47 UTC, sna2021 commented on packages/feature_flags/lib/domain/feature_flag.dart
> +  FeatureFlag(FeatureFlagState initState) : state = initState;
Согласно линтнеру конструкторы должны быть выше переменных. 

Посмотреть можно здесь в readme.

https://github.com/smmarty/friflex_flutter/tree/main/packages/friflex_lint_rules

2022-09-20 16:47 UTC, sna2021 commented on packages/feature_flags/lib/domain/features_manager.dart
> +    init();
В целом не очень хорошая практика вызывать что либо в дефолтных конструкторах. 
1. Это не явно. 
2. Перегружает инстанцирование объектов. 

если нужно что-то делать при создании объекта, то лучше создавать под это именованные конструкторы либо factory. Это будет более явно.

2022-09-20 16:47 UTC, sna2021 commented on packages/feature_flags/lib/domain/features_manager.dart
> +  void updateFlag(String name, FeatureFlagState newState) {
Лучше использовать именованные параметры

2022-09-20 16:47 UTC, sna2021 commented on packages/feature_flags/lib/domain/features_manager.dart
> +    } on Exception catch (_) {
тут try/catch не играет никакой роли, его можно убрать

2022-09-20 16:47 UTC, sna2021 commented on packages/feature_flags/lib/domain/features_manager.dart
> +  void setFlags(Map<String, FeatureFlag> newFlags) {
Этот метод не нужен, его функционал возьмет конструктор

2022-09-20 16:47 UTC, sna2021 commented on packages/feature_flags/lib/domain/features_manager.dart
> +    init();
Тут лучше будет передать в конструкторе Iterable<FeatureFlag> flags; 

и в конструкторе их можно преобразовать в Map<Type,FeatureFlag>

2022-09-20 16:47 UTC, sna2021 commented on packages/feature_flags/lib/feature_flags.dart
> +library feature_flags;
По структуре package нужно все остальные папки и файлы вынести в src папку, иначе они все равно будут доступны и смысл этого файла теряется.

2022-09-20 16:47 UTC, sna2021 commented on packages/feature_flags/test/feature_flags_test.dart
> +Future<void> testFlags() async {
Полноценный тест должен содержать в себе. 
1. Ожидаемое состояние.
2. Действие. 
3. Проверку на то соответствуют ли полученное состояние ожидаемому. 

Лучше не выносить тело теста в отдельный метод. 

Если нужна консультация по тестированию - напиши, устроим созвон.

2022-09-20 16:47 UTC, sna2021 commented on packages/feature_flags/test/feature_flags_test.dart
> +import 'package:flutter/cupertino.dart';
import 'package:flutter/cupertino.dart';

старайся следить за импортами :)

2022-09-20 16:48 UTC, inoek requested changes

2022-09-20 16:48 UTC, inoek commented on packages/feature_flags/lib/domain/feature_flag.dart
> +  FeatureFlag(FeatureFlagState initState) : state = initState;
Внутри класса используется следующий порядок:
1. Конструктор класса
2. Именованные конрструкторы класса
3. Фабричные конрструкторы класса
4. Публичные static const поля
5. Приватные static const поля
6. Публичные static поля
7. Приватные static поля
8. Публичные final поля
9. Приватные final поля
10. Публичные поля (get/set)
11. Приватные поля (get/set)
12. @override методы
13. Публичные static методы
14. Публичные методы
15. @protected методы
16. Приватные static методы
17. Приватные методы

2022-09-20 16:48 UTC, inoek commented on packages/feature_flags/lib/domain/features_manager.dart
> +  void updateFlag(String name, FeatureFlagState newState) {
если больше одного параметра - делаем именованные

2022-09-20 16:48 UTC, inoek commented on packages/feature_flags/lib/domain/feature_flag.dart
> +  FeatureFlagState? state;
сделай через final

2022-09-20 16:48 UTC, inoek commented on packages/feature_flags/lib/domain/features_manager.dart
> +  @protected
аналогично про порядок)

2022-09-20 16:48 UTC, inoek commented on packages/feature_flags/lib/domain/features_manager.dart
> +  void updateFlag(String name, FeatureFlagState newState) {
name => key

2022-09-20 16:48 UTC, inoek commented on packages/feature_flags/lib/domain/features_manager.dart
> +      rethrow;
throw error

2022-09-20 16:48 UTC, inoek commented on packages/feature_flags/test/feature_flags_test.dart
> +class MyFlag extends FeatureFlag {
респект за тест)

2022-09-20 16:49 UTC, inoek commented on packages/feature_flags/test/feature_flags_test.dart
> +Future<void> testFlags() async {
я бы в example вынес

2022-09-21 12:46 UTC, sna2021 reviewed
2 правки и первый этап готов

2022-09-21 12:46 UTC, sna2021 commented on packages/feature_flags/test/feature_flags_test.dart
> +      assert(myManager.flags[MyFlag1]?.state == FeatureFlagState.enabled);
в тестах используется expect() для проверки

2022-09-21 12:46 UTC, sna2021 commented on packages/feature_flags/lib/src/domain/features_manager.dart
> +    flags[type]?.state = newState;
а вот тут можно как раз добавить assert(flags[type] != null)

2022-09-21 12:56 UTC, merged